### ISSUE TITLE
怎么关掉日志？

### ISSUE THREAD

**Issue by maoxianfly** [Baidu-ecom/Jprotobuf-rpc-socket#25]
十二月 04, 2015 11:04:37 上午 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler doCompile
信息: Begin to compile source code: class is 'com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass'
十二月 04, 2015 11:04:41 上午 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler doCompile
信息: compile source code done: class is 'com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass'
十二月 04, 2015 11:04:41 上午 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler doCompile
信息: loading class 'com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass'
十二月 04, 2015 11:04:41 上午 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler doCompile
信息: loading class done  'com.baidu.bjf.remoting.protobuf.descriptor.FileDescriptorProtoPOJO$$JProtoBufClass'
十二月 04, 2015 11:04:41 上午 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler doCompile

怎么这些关掉日志？

**Comment by xiemalin** [comment]
这一块的日志是由log4j输出，目前关掉的话，只能要log4j配置中，把 com.baidu.bjf.remoting.protobuf.utils.compiler.JdkCompiler的日志级别设置到info级别以上，如warn即可
