### ISSUE TITLE
redis 的自动发现只有测试xml 很难懂

### ISSUE THREAD

**Issue by dylanliang** [Baidu-ecom/Jprotobuf-rpc-socket#26]
可以更新一下说明 怎么配置redis 自动发现么

**Comment by xiemalin** [comment]
这一块的具体使用文档会尽快更新出来，请后续关注，谢谢！

**Comment by dylanliang** [comment]
是因为项目还在改进中api 变动的关系么.只需要一个简单的说明就可以了

**Comment by xiemalin** [comment]
说明已更新 
参见： https://github.com/Baidu-ecom/Jprotobuf-rpc-socket/wiki/User-Guide
