### ISSUE TITLE
jprotobuf在并发情况下好似性能很差

### ISSUE THREAD

**Issue by wangzheng0822** [Baidu-ecom/Jprotobuf-rpc-socket#37]
对于一个rpc service, 通过多线程同时并发调用相同方法，响应时间随着并发数迅速上升，并发情况下性能极差，是否是合理的呢？

**Comment by jhunters** [comment]
性能极差 的具体数值有吗？ 如果调用相同方法，需要看这个方法做什么事情，方法本身有什么并发的能力，如果一个方向本身并发是N，那最大的rpc并发理论上也只能少于N了

**Comment by wangzheng0822** [comment]
service.echo方法，方法里面sleep(50ms)模拟逻辑处理，然后客户端启动100线程来并发远程调用service.echo rpc方法，客户端来统计每个请求的响应时间，发现每个请求的时间依次递增，从200ms一直到1s，并非感觉到是并发执行的，如果是并发执行，按理来说每个请求的响应时间应该都比较一直，而且也不应该有时间到１ｓ的情况呀

**Comment by wangzheng0822** [comment]
加个微信问问吧，我微信号就是github id号，我在之前公司的时候用stubby没有出现过类似问题，现在公司用的jprotobuf，才开始用，好像也没人懂

**Comment by jhunters** [comment]
有两个地方需要设置，一个是客户端的线程数， 在RpcClientOptions中设置  threadPoolSize 默认是20,超过会排队, 另一个在服务端设置work线程数, 在 RpcServerOptions的 workThreads 默认是 cpu核数*2 ,超过会排队，请检查这两块的设置值

**Comment by wangzheng0822** [comment]
好的，貌似我也都设置了，workhreads=20, threadpoolsize=50,我在研究一下是不是设置的不对没生效，我再试试，待会反馈：）

**Comment by wangzheng0822** [comment]
还有acceptThreads设置成１ok吗？需要特殊设置吗?

**Comment by jhunters** [comment]
还有acceptThreads设置成１ok吗？需要特殊设置吗?  可以的

**Comment by wangzheng0822** [comment]
还是一样慢呢

COST TIME:522, REQCOUNT:1
COST TIME:398, REQCOUNT:2
COST TIME:399, REQCOUNT:3
COST TIME:429, REQCOUNT:4
COST TIME:550, REQCOUNT:5
COST TIME:469, REQCOUNT:6
COST TIME:477, REQCOUNT:7
COST TIME:470, REQCOUNT:9
COST TIME:481, REQCOUNT:11
COST TIME:464, REQCOUNT:8
COST TIME:433, REQCOUNT:10
COST TIME:433, REQCOUNT:12
COST TIME:565, REQCOUNT:13
COST TIME:438, REQCOUNT:14
COST TIME:472, REQCOUNT:15
COST TIME:513, REQCOUNT:16
COST TIME:514, REQCOUNT:17
COST TIME:514, REQCOUNT:18
COST TIME:515, REQCOUNT:19
COST TIME:508, REQCOUNT:20
COST TIME:540, REQCOUNT:21
COST TIME:555, REQCOUNT:22
COST TIME:556, REQCOUNT:23
COST TIME:558, REQCOUNT:24
COST TIME:591, REQCOUNT:25
COST TIME:559, REQCOUNT:26
COST TIME:591, REQCOUNT:28
COST TIME:582, REQCOUNT:29
COST TIME:577, REQCOUNT:30
COST TIME:590, REQCOUNT:27
COST TIME:593, REQCOUNT:31
COST TIME:570, REQCOUNT:32
COST TIME:588, REQCOUNT:33
COST TIME:588, REQCOUNT:34
COST TIME:588, REQCOUNT:35
COST TIME:612, REQCOUNT:36
COST TIME:602, REQCOUNT:37
COST TIME:614, REQCOUNT:38
COST TIME:629, REQCOUNT:39
COST TIME:615, REQCOUNT:40
COST TIME:622, REQCOUNT:41
COST TIME:623, REQCOUNT:42
COST TIME:629, REQCOUNT:43
COST TIME:672, REQCOUNT:44
COST TIME:630, REQCOUNT:45
COST TIME:589, REQCOUNT:46
COST TIME:637, REQCOUNT:47
COST TIME:637, REQCOUNT:48
COST TIME:686, REQCOUNT:49
COST TIME:623, REQCOUNT:50
COST TIME:683, REQCOUNT:51
COST TIME:696, REQCOUNT:52
COST TIME:697, REQCOUNT:53
COST TIME:697, REQCOUNT:54
COST TIME:667, REQCOUNT:55
COST TIME:667, REQCOUNT:56
COST TIME:702, REQCOUNT:57
COST TIME:673, REQCOUNT:59
COST TIME:689, REQCOUNT:58
COST TIME:686, REQCOUNT:60
COST TIME:681, REQCOUNT:61
COST TIME:680, REQCOUNT:62
COST TIME:697, REQCOUNT:63
COST TIME:694, REQCOUNT:64
COST TIME:694, REQCOUNT:65
COST TIME:736, REQCOUNT:66
COST TIME:778, REQCOUNT:67
COST TIME:718, REQCOUNT:68
COST TIME:718, REQCOUNT:69
COST TIME:738, REQCOUNT:70
COST TIME:760, REQCOUNT:71
COST TIME:778, REQCOUNT:72
COST TIME:817, REQCOUNT:73
COST TIME:854, REQCOUNT:74
COST TIME:901, REQCOUNT:75
COST TIME:926, REQCOUNT:76
COST TIME:905, REQCOUNT:77
COST TIME:985, REQCOUNT:78
COST TIME:1010, REQCOUNT:79
COST TIME:1055, REQCOUNT:80
COST TIME:1067, REQCOUNT:81
COST TIME:1178, REQCOUNT:82
COST TIME:1134, REQCOUNT:83
COST TIME:1154, REQCOUNT:84
COST TIME:1188, REQCOUNT:85
COST TIME:1225, REQCOUNT:86

**Comment by wangzheng0822** [comment]
List<Thread> list = new ArrayList<Thread>();
    for (int i = 0; i < 100; ++i) {
      Thread t = new Thread() {
        @Override
        public void run() {
          HelloWorldRequest request = new HelloWorldRequest();
          request.requestMessage = "hello";
          long startTime = System.currentTimeMillis();
          HelloWorldResponse response = helloworldService.hello(request);
          long costTime = System.currentTimeMillis() - startTime;
          reqCount.incrementAndGet();
          System.out.println("COST TIME:" + costTime + ", REQCOUNT:" + reqCount);
        }
      };
      list.add(t);
    }
    for (int i = 0; i < list.size(); ++i) {
      list.get(i).start();
    }

**Comment by wangzheng0822** [comment]
server:
    RpcServerOptions options = new RpcServerOptions();
    options.setWorkThreads(50);
    RpcServer server = new RpcServer(options);
    HelloWorldServiceImpl helloWorldServiceImpl = new HelloWorldServiceImpl();
    server.registerService(helloWorldServiceImpl);
    server.start(10031);

client:

    RpcClientOptions options = new RpcClientOptions();
    options.setThreadPoolSize(50);
    RpcClient rpcClient = new RpcClient(options);
    rpcProxy = new ProtobufRpcProxy<HelloWorldService>(rpcClient, HelloWorldService.class);
    rpcProxy.setPort(10031);
    helloworldService = rpcProxy.proxy();

**Comment by jhunters** [comment]
稍等，我确认一下，稍后回复

**Comment by jhunters** [comment]
HelloWorldServiceImpl HelloWorldService的代码也贴一下

**Comment by wangzheng0822** [comment]
public interface HelloWorldService {
	@ProtobufRPC(serviceName = "helloWorldService")
	HelloWorldResponse hello(HelloWorldRequest request);
}



public class HelloWorldServiceImpl implements HelloWorldService {

  @Override
  @ProtobufRPCService(serviceName = "helloWorldService")
  public HelloWorldResponse hello(HelloWorldRequest request) {
    try {
      Thread.sleep(50);
    } catch (InterruptedException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    String requestMessage = request.requestMessage;
    String responseMessage = requestMessage + "-RESPONSE";
    HelloWorldResponse response = new HelloWorldResponse();
    response.responseMessage = responseMessage;
    return response;
  }
}

**Comment by wangzheng0822** [comment]
非并发请求下，测试的tps在几千，１０个线程并发下，ｔｐｓ上万，但当并发数继续增大之后，发现响应时间和tps下降严重

**Comment by wangzheng0822** [comment]
提供另一组数据：
    List<Thread> list = new ArrayList<Thread>();
    for (int i = 0; i < 5; ++i) {
      Thread t = new Thread() {
        @Override
        public void run() {
          HelloWorldRequest request = new HelloWorldRequest();
          request.requestMessage = "hello";
          for (int j = 0; j < 100; ++j) {
            long startTime = System.currentTimeMillis();
            HelloWorldResponse response = helloworldService.hello(request);
            long costTime = System.currentTimeMillis() - startTime;
            reqCount.incrementAndGet();
            System.out.println("COST TIME:" + costTime + ", REQCOUNT:" + reqCount);
          }
        }
      };
      list.add(t);
    }
    for (int i = 0; i < list.size(); ++i) {
      list.get(i).start();
    }

发现有５个rpc调用响应时间很慢，对应５个线程，每个线程第一个rpc请求都很慢，之后都很快，难道实在寻址？
**COST TIME:342, REQCOUNT:1**
**COST TIME:368, REQCOUNT:2**
COST TIME:53, REQCOUNT:3
**COST TIME:411, REQCOUNT:4**
COST TIME:53, REQCOUNT:5
COST TIME:55, REQCOUNT:6
**COST TIME:453, REQCOUNT:7**
COST TIME:87, REQCOUNT:8
COST TIME:76, REQCOUNT:9
COST TIME:54, REQCOUNT:10
**COST TIME:537, REQCOUNT:11**
COST TIME:97, REQCOUNT:12
COST TIME:52, REQCOUNT:13
COST TIME:52, REQCOUNT:14
COST TIME:52, REQCOUNT:15
COST TIME:52, REQCOUNT:16
COST TIME:53, REQCOUNT:18
COST TIME:52, REQCOUNT:18
COST TIME:53, REQCOUNT:19
COST TIME:53, REQCOUNT:20
COST TIME:53, REQCOUNT:21
COST TIME:52, REQCOUNT:22
COST TIME:52, REQCOUNT:24
COST TIME:52, REQCOUNT:23
COST TIME:53, REQCOUNT:25

**Comment by jhunters** [comment]
不是，应该找到你的原因了，是第一次的连接耗时，你的并发很大时候，创建连接的成本很高，之后是长链接，就没有这个问题了

**Comment by wangzheng0822** [comment]
那这个问题有解决办法吗？并发请求应该是比较常见的，而且好像几十的并发的时候也很慢．

**Comment by wangzheng0822** [comment]
３0个并发的情况下：
COST TIME:351, REQCOUNT:1
COST TIME:388, REQCOUNT:2
COST TIME:431, REQCOUNT:3
COST TIME:463, REQCOUNT:4
COST TIME:506, REQCOUNT:5
COST TIME:530, REQCOUNT:6
COST TIME:558, REQCOUNT:7
COST TIME:592, REQCOUNT:8
COST TIME:631, REQCOUNT:9
COST TIME:668, REQCOUNT:10
COST TIME:712, REQCOUNT:11
COST TIME:738, REQCOUNT:12
COST TIME:764, REQCOUNT:13
COST TIME:800, REQCOUNT:14
COST TIME:818, REQCOUNT:15
COST TIME:848, REQCOUNT:16
COST TIME:888, REQCOUNT:17
COST TIME:911, REQCOUNT:18
COST TIME:945, REQCOUNT:19
COST TIME:987, REQCOUNT:20
1473306368682, tps: 19,  count: 20, success: 0 , error: 0
COST TIME:1009, REQCOUNT:21
COST TIME:1037, REQCOUNT:22
COST TIME:1080, REQCOUNT:23
COST TIME:1094, REQCOUNT:24
COST TIME:1121, REQCOUNT:25
COST TIME:1139, REQCOUNT:26
COST TIME:1172, REQCOUNT:27
COST TIME:1196, REQCOUNT:28
COST TIME:1230, REQCOUNT:29
COST TIME:1254, REQCOUNT:30

**Comment by wangzheng0822** [comment]
链接的建立是顺序建立的吗？为啥这么慢呢？

**Comment by jhunters** [comment]
这个是操作系统控制了，主要的问题你的连接创建是并发下一起过来的，理解上只能是顺序的做的. 你也可以调整一下serverRpcOptions的acceptorThreads参数设置看看

**Comment by wangzheng0822** [comment]
链接建立之后用完会释放吗？有参数可以控制吗？

**Comment by jhunters** [comment]
可以控制，在RpcClientOptions这个配置中
    /** The thread pool size. */
    private int threadPoolSize = 20;
    
    /** The max idle size. */
    private int maxIdleSize = 20;
    
    /** The min idle size. */
    private int minIdleSize = 2;

**Comment by wangzheng0822** [comment]
：）多谢～
