### ISSUE TITLE
连接在60s之后断开，并未保持

### ISSUE THREAD

**Issue by wangzheng0822** [Baidu-ecom/Jprotobuf-rpc-socket#43]
做了一下测试：

在一个函数里面:

STEP 1: 第一次RPC调用，建立链接如下：
tcp6       0      0 :::18801                :::*                    LISTEN      31958/java      
tcp6       0      0 127.0.0.1:18801         127.0.0.1:49116         ESTABLISHED 31958/java      
tcp6       0      0 127.0.0.1:49116         127.0.0.1:18801         ESTABLISHED 3053/java   

STEP2: 然后程序sleep(80s), 在大约sleep了60s之后观察链接：已经被客户端关闭？
tcp6       0      0 :::18801                :::*                    LISTEN      31958/java      
tcp6       0      0 127.0.0.1:18801         127.0.0.1:49116         TIME_WAIT   -    

STEP3: 然后程序再次发起RPC请求,查看链接：重新建立了新的链接！
tcp6       0      0 :::18801                :::*                    LISTEN      31958/java      
tcp6       0      0 127.0.0.1:18801         127.0.0.1:49126         ESTABLISHED 31958/java      
tcp6       0      0 127.0.0.1:49126         127.0.0.1:18801         ESTABLISHED 3053/java       
tcp6       0      0 127.0.0.1:18801         127.0.0.1:49116         TIME_WAIT   - 

我的理解是链接建立之后一直保持着呀，为什么60s后会断掉（貌似是被客户端关闭的）

**Comment by wangzheng0822** [comment]
我的client端配置：

```
<bean id="userProfileRpcService" class="com.baidu.jprotobuf.pbrpc.spring.HaRpcProxyFactoryBean"
          p:serviceInterface="com......UserProfileRpcService"
          p:onceTalkTimeout="20000"
          p:lookupStubOnStartup="false"
          p:idleTimeout="600"
          p:keepAlive="true"
          p:shortConnection="false"
          p:threadPoolSize="50"
          p:namingService-ref="remoteEyrieNamingService"/>
```

**Comment by wangzheng0822** [comment]
server端配置：
```
    <util:list id="registerServices">
        <ref bean="userProfileRpcServiceImpl"/>
    </util:list>

    <bean class="com.baidu.jprotobuf.pbrpc.spring.RpcServiceExporter"
          p:servicePort="...."
          p:acceptorThreads="1"
          p:workThreads="15"
          p:registerServices-ref="registerServices"/>`
```

**Comment by jhunters** [comment]
我的理解是链接建立之后一直保持着呀，为什么60s后会断掉（貌似是被客户端关闭的） 应该是服务端关闭的，RpcServerOptions有几个参数需要注意 readerIdleTime  writerIdleTime   keepAliveTime 对应的就是读空闲关闭，写空闲关闭与 读写空闲关闭 目默认值是 60s

**Comment by wangzheng0822** [comment]
看代码了，我知道了，idleTime最大值不超过60，我设置了600也不起作用啦

**Comment by wangzheng0822** [comment]
哦哦　明白了　刚也看了代码　清楚了　多谢了
